CREATE TABLE user
(
    id SERIAL NOT NULL PRIMARY KEY,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    created_at datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP) ON UPDATE CURRENT_TIMESTAMP
);
